baseURL = "https://jp-weber.family/"
languageCode = "de-at"
title = "Familie Weber: Paul, J, K, F und A"
theme = 'ezhil'

copyright = "© Paul Weber"

# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Number of posts to show in recent posts list (Optional). Defaults to 10.
pagination.pagerSize = 10



[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true



[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "Texte übers Radfahren, Programmieren und Kochen"

    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page"]


    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "/icons/jpkw.png"

    # Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
    mode = "auto" # "dark" or "auto"

    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
    customCSS = "css/custom.css"
    # Custom CSS added to dark mode style.
    customDarkCSS = "css/custom-dark.css"

    # Custom list of Javascript files to load. Just like custom CSS you can place js files under
    # `static/js` folder and specify path here as `js/script-name.js`.
    # customJS = ["js/abc.js", "js/xyz.js"]

# Main menu which appears below site header.
[[menu.main]]
name = "Blog"
url = "/"
weight = 1

#[[menu.main]]
#name = "Alle Artikel"
#url = "/posts"
#weight = 2

[[menu.main]]
name = "Über Paul Weber"
url = "/paul-weber"
weight = 3

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "/icons/github.svg"
url = "https://github.com/000panther"

[[params.social]]
name = "Mastodon"
icon = "/icons/mastodon.svg"
url = "https://ooe.social/@000panther"
rel = "me"

# Enable tags.
[taxonomies]
   tag = "tags"
